name: Deploy client user

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: ./frontend/client

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_API_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Netlify Production deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true